meta_name: "LSA PARIS"
meta_title: "LSA PARIS - Conseil Contentieux Médiation Arbitrage"
meta_description: "Rodolphe : description de base pour LSA poster sur les Réseaux Sociaux"
meta_image: "LSA-PARIS-LOGO.jpg" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
